name: Deploy

on:
  - push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: package
        run: zip artifact.zip main.py

      - name: push to s3
        run: aws s3 cp artifact.zip s3://terraform-20230322013953818100000001/artifact.zip 

      - name: update function code
        run: aws lambda update-function-code --function-name cicd --s3-bucket terraform-20230322013953818100000001 --s3-key artifact.zip